_id: d779730c7cc94155877a24e2e8be2ad1
created: '2024-07-11T15:07:59.993188'
description: Built-in IDAES workspace
htmldocs:
- https://idaes-pse.readthedocs.io/en/stable
- '{dmf_root}/docs/build/html'
modified: '2024-07-11T15:07:59.993188'
name: IDAES
